prajwal

In [30]:
import numpy as np 
import pandas as pd 
import  matplotlib.pyplot as plt 
import seaborn as sns

In [31]:
from sklearn.metrics import mean_squared_error,r2_score
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor,AdaBoostRegressor
from sklearn.svm import SVR
from sklearn.linear_model import LinearRegression,Ridge,Lasso
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error
from sklearn.model_selection import RandomizedSearchCV
from catboost import CatBoostRegressor 
from xgboost import XGBRegressor
import warnings

In [32]:
df=pd.read_csv(r'C:\Users\prajw\OneDrive\Desktop\macine learning project 01\notebook\data\StudentsPerformance.csv')

In [33]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [34]:
x=df.drop(columns=['math score'],axis=1)

In [35]:
y=df["math score"]

In [36]:
x.head(2)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,74
1,female,group C,some college,standard,completed,90,88

In [37]:
print("categorical feature in unique is the :",end=" ")
print(x["gender"].unique())
print("categorical feature in a uniques raceend ethnicity is: ",end=" ")
print(x["race/ethnicity"].unique())
print("categorical feature in a parental level of education :",end=" ")
print(x["parental level of education"].unique())
print("categorical feature in a lunch : ",end=" ")
print(x["lunch"].unique())
print("categorical feature in a test preparation course : ",end=" ")
print(x["test preparation course"].unique())

categorical feature in unique is the : ['female' 'male']
categorical feature in a uniques raceend ethnicity is:  ['group B' 'group C' 'group A' 'group D' 'group E']
categorical feature in a parental level of education : ["bachelor's degree" 'some college' "master's degree" "associate's degree"
 'high school' 'some high school']
categorical feature in a lunch :  ['standard' 'free/reduced']
categorical feature in a test preparation course :  ['none' 'completed']

In [38]:
y.head(2)

0    72
1    69
Name: math score, dtype: int64

In [39]:
num_feature=x.select_dtypes(exclude="object").columns
cat_feature=x.select_dtypes(include="object").columns
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.compose import ColumnTransformer
numeric_transformer=StandardScaler()
onehotencoding_transformer=OneHotEncoder()

preprocessor=ColumnTransformer(
    [
        ("OneHotEncoder",onehotencoding_transformer,cat_feature),
        ("standardscaler",numeric_transformer,num_feature)


    ]
)

In [40]:

x=preprocessor.fit_transform(x)

In [41]:
x.shape

(1000, 19)

In [42]:
from sklearn.model_selection import train_test_split

In [43]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
x_train.shape,x_test.shape

((800, 19), (200, 19))

In [44]:
def evaluate_model(true,predicted):
    mae=mean_absolute_error(true,predicted)
    mse=mean_squared_error(true,predicted)
    rmse=np.sqrt(mean_squared_error(true,predicted))
    r2_score=r2_score(true,predicted)
    return mae,mse,rmse,r2_score